/**

 * JSON 逻辑模块 `details/recruit-tickets/recruit-tickets` 的 Zod Schema。

 */

import { z } from "zod";

import type {
  ExtraCharId,
  RecruitTickets,
  Rogue1_RecruitTicket5StarClass,
  Rogue1_RecruitTicketAllClass,
  Rogue1_RecruitTicketCasterClass,
} from "../../../../types/roguelike-topic-table/details/recruit-tickets/recruit-tickets.types.js";

import { CategorySchema } from "../../shared/common-enums.schemas.js";

import {
  ProfessionSchema,
  RarityListSchema,
} from "../../shared/item-enums.schemas.js";

/**
 * roguelike_topic_table.json 中 ExtraCharId 的运行时校验结构。
 */
export const ExtraCharIdSchema = z
  .enum([
    "char_504_rguard",
    "char_507_rsnipe",
    "char_505_rcast",
    "char_506_rmedic",
    "char_514_rdfend",
  ])
  .describe(
    "roguelike_topic_table.json 中 ExtraCharId 的运行时校验结构。",
  ) satisfies z.ZodType<ExtraCharId>;

/**
 * roguelike_topic_table.json 中 Rogue1_RecruitTicket5StarClass 的运行时校验结构。
 */
export const Rogue1_RecruitTicket5StarClassSchema = z
  .strictObject({
    id: z.string(),
    profession: z.number(),
    rarity: z.number(),
    professionList: z.array(ProfessionSchema),
    rarityList: z.array(RarityListSchema),
    extraEliteNum: z.number(),
    extraFreeRarity: z.array(z.never()),
    extraCharIds: z.array(ExtraCharIdSchema),
  })
  .describe(
    "roguelike_topic_table.json 中 Rogue1_RecruitTicket5StarClass 的运行时校验结构。",
  ) satisfies z.ZodType<Rogue1_RecruitTicket5StarClass>;

/**
 * roguelike_topic_table.json 中 Rogue1_RecruitTicketAllClass 的运行时校验结构。
 */
export const Rogue1_RecruitTicketAllClassSchema = z
  .strictObject({
    id: z.string(),
    profession: z.number(),
    rarity: CategorySchema,
    professionList: z.array(ProfessionSchema),
    rarityList: z.array(RarityListSchema),
    extraEliteNum: z.number(),
    extraFreeRarity: z.array(z.never()),
    extraCharIds: z.array(ExtraCharIdSchema),
  })
  .describe(
    "roguelike_topic_table.json 中 Rogue1_RecruitTicketAllClass 的运行时校验结构。",
  ) satisfies z.ZodType<Rogue1_RecruitTicketAllClass>;

/**
 * roguelike_topic_table.json 中 Rogue1_RecruitTicketCasterClass 的运行时校验结构。
 */
export const Rogue1_RecruitTicketCasterClassSchema = z
  .strictObject({
    id: z.string(),
    profession: ProfessionSchema,
    rarity: CategorySchema,
    professionList: z.array(ProfessionSchema),
    rarityList: z.array(RarityListSchema),
    extraEliteNum: z.number(),
    extraFreeRarity: z.array(RarityListSchema),
    extraCharIds: z.array(ExtraCharIdSchema),
  })
  .describe(
    "roguelike_topic_table.json 中 Rogue1_RecruitTicketCasterClass 的运行时校验结构。",
  ) satisfies z.ZodType<Rogue1_RecruitTicketCasterClass>;

/**
 * roguelike_topic_table.json 中 RecruitTickets 的运行时校验结构。
 */
export const RecruitTicketsSchema = z
  .strictObject({
    rogue_1_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_1_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_1_recruit_ticket_pioneer_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_warrior_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_tank_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_sniper_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_caster_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_support_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_medic_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_1_recruit_ticket_redecial_red:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_pioneer_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_warrior_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_tank_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_sniper_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_caster_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_support_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_medic_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_special_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_2_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_2_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_temp_5_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_2_recruit_ticket_temp_6_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_pioneer_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_warrior_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_tank_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_sniper_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_caster_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_support_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_medic_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_special_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_3_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_3_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_temp_5_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_3_recruit_ticket_temp_6_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_pioneer_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_warrior_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_tank_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_sniper_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_caster_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_support_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_medic_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_special_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_4_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_1_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_2_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_3_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_double_4_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_4_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_temp_5_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_temp_6_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_4_recruit_ticket_temp_6:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_1_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_2_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_3_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_4_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_5_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_5_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_6_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_6:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_double_1_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_2_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_3_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_4_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_1_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_2_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_3_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_double_4_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_melee_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_ranged_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_all_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_5star_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_5_recruit_ticket_all_premium_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_melee_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_quad_ranged_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_all_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_5_up_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_6_up_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_temp_6_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_pioneer_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_warrior_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_tank_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_sniper_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_caster_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_support_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_medic_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_special_vip_init:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_5_recruit_ticket_only_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special_sp:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special_vip:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_double_1:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_2:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_3:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_4:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_1_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_2_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_3_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_4_vip:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_melee:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_ranged:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_all: Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_5star:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_all_premium:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_melee_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_ranged_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_all_discount:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_5_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_6_up:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_6:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_1_vip:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_2_vip:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_3_vip:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_4_vip:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special_sp_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_pioneer_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_warrior_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_tank_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_sniper_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_caster_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_support_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_medic_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_special_vip_candle:
      Rogue1_RecruitTicketCasterClassSchema.optional(),
    rogue_6_recruit_ticket_double_1_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_2_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_3_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_4_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_1_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_2_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_3_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_double_4_vip_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_melee_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_ranged_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_all_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_5star_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_all_premium_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_melee_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_quad_ranged_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_all_discount_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_5_up_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_6_up_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_temp_6_candle:
      Rogue1_RecruitTicketAllClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_1_vip_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_2_vip_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_3_vip_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
    rogue_6_recruit_ticket_5star_double_4_vip_candle:
      Rogue1_RecruitTicket5StarClassSchema.optional(),
  })
  .describe(
    "roguelike_topic_table.json 中 RecruitTickets 的运行时校验结构。",
  ) satisfies z.ZodType<RecruitTickets>;
