/**
 * 编译期断言显式 TypeScript 类型与对应 Zod 推导类型完全一致。
 */

import { z } from "zod";

import type {
  RoguelikeTopicTable,
  Constant,
  PredefinedChar,
  RecruitType,
  CustomizeDatum,
  CommonDevelopment,
  CommonDevelopmentDevelopmentRawTextGroup,
  GroupIconId,
  Rogue3__Difficulty1,
  BuffDisplayInfo,
  DisplayForm,
  EffectType,
  EnrollId,
  GroupId,
  ValidModeEnum,
  CommonDevelopmentDevelopmentsDifficultyNodeInfos,
  Rogue4_Difficulty1_Class,
  Rogue4_Difficulty1_NodeMap,
  DevelopmentToken,
  DevelopmentLine,
  CustomizeDatumDevelopmentRawTextGroup,
  Developments,
  Outbuff,
  BuffIconId,
  Outbuff1_NodeType,
  Rogue2__Outbuff,
  Rogue2_Outbuff1_NodeType,
  CustomizeDatumDevelopmentsDifficultyNodeInfos,
  Rogue3__Difficulty,
  Rogue3_Difficulty1_NodeMap,
  CustomizeDatumDifficulty,
  GildProbDisplay,
  LeftDisasterDesc,
  LeftOverweightDesc,
  LeftWeatherDesc,
  LeftWrathDesc,
  Mode,
  SkyStepDescription,
  WeightStatusLimitDesc,
  EmployShopDialogData,
  EmployShopDialogDataTypes,
  BuyConfirm,
  BuyConfirmGroups,
  None,
  PurpleBuySelect,
  PurpleGroups,
  EndingText,
  ScrapShopDialogData,
  ScrapShopDialogDataTypes,
  SpecialShopDialog,
  SpecialShopDialogTypes,
  FluffyBuySelect,
  FluffyGroups,
  Detail,
  Activity,
  ActivityTable,
  SeedMode,
  SeedModeRogue4_Seedmode1,
  ConstData,
  OfficialSeedDataList,
  BasicDatas,
  BasicDatasRogue4_Seedmode1,
  ArchiveComp,
  ArchiveCompBuff,
  BuffValue,
  BuffColor,
  ArchiveCompCapsule,
  CapsuleValue,
  ArchiveCompChaos,
  Chao,
  ArchiveCompChat,
  ChatValue,
  ChatItemList,
  ZoneId,
  ArchiveCompCopper,
  CopperTypes,
  Blank,
  CopperType,
  CopperValue,
  CopperArchiveType,
  CopperGildTypeDatum,
  Id,
  LuckyLevels,
  High,
  LuckyLevel,
  ArchiveCompDisaster,
  DisasterValue,
  ArchiveCompEndbook,
  EndbookValue,
  ClientEndbookItemData,
  ArchiveCompFragment,
  FragmentValue,
  ArchiveCompRelic,
  RelicRelic,
  ArchiveCompScrap,
  ScrapValue,
  ArchiveCompTotem,
  TotemValue,
  Pos,
  ArchiveCompTrap,
  TrapTrap,
  Rogue1__ActiveTool,
  ArchiveCompWeather,
  WeatherValue,
  ArchiveCompWrath,
  WrathValue,
  ArchiveUnlockCond,
  ArchiveUnlockCondEnroll,
  EnrollArchiveType,
  UnlockCondDesc,
  UnlockCondDescDescription,
  BandRef,
  BankReward,
  RewardId,
  RewardType,
  BattleLoadingTip,
  Category,
  BattleSummeryDescriptions,
  ChallengeClass,
  CapsuleDict,
  ChallengeElement,
  ChallengeTask,
  Reward,
  ItemTypeEnum,
  CharBuffData,
  Rogue2_Mutation1_Class,
  Rogue2_Mutation1_BuffType,
  BuffElement,
  Blackboard,
  Rogue2__Mutation4,
  ChoiceScene,
  TitleIcon,
  Choice,
  DisplayData,
  THintType,
  IconEnum,
  DisplayDataType,
  LeftDecoType,
  Rogue6_ScrapM01_Enum,
  CustomTickets,
  Rogue2_CustomTicketPurifyClass,
  DetailConst,
  CharUpgradeTable,
  EvolvePhase,
  HistoricalRecordsMode,
  PlayerLevelTable,
  PredefinedLevelTable,
  DetailDifficulty,
  DisplayIconId,
  FailForceDesc,
  FailTitle,
  NameImage,
  RuleDescReplacement,
  DifficultyUpgradeRelicGroup,
  RelicDatum,
  EndingDetailList,
  EventType,
  EndingDetailListShowType,
  SpZoneEvtType,
  EndingRelicDetailList,
  Ending,
  IconElement,
  DetailEnroll,
  EnrollType,
  ExploreTools,
  Rogue3__ExploreTool1,
  FailEndings,
  Ro4FailEnding1,
  IconId,
  FusionData,
  Variation,
  GameConst,
  ItemDropTagDict,
  BgmSignal,
  GrandPrize,
  Init,
  StyleId,
  Item,
  ObtainApproach,
  Rarity,
  SubType,
  TinyIconColor,
  RewardItemTypeEnum,
  LegacyItem,
  MilestoneUpdate,
  Milestone,
  MonthMission,
  TaskClass,
  MonthSquad,
  MonthTeam,
  TeamChar,
  NodeTypeDatum,
  RecruitTickets,
  Rogue1_RecruitTicket5StarClass,
  ExtraCharId,
  Profession,
  RarityList,
  Rogue1_RecruitTicketAllClass,
  Rogue1_RecruitTicketCasterClass,
  RelicParam,
  CheckCharBoxParam,
  CheckCharBoxType,
  RelicTipsData,
  Rogue5__,
  DetailRelic,
  RollNodeData,
  Zone,
  Zone1_Groups,
  BattleElite,
  NodeTypeElement,
  ZonePortalNormal5_,
  ZonePortalNormal5_1_Groups,
  ZonePortalRevival,
  ZonePortalRevival3_Groups,
  ShopDialogData,
  ShopDialogDataTypes,
  SquadBuffData,
  Stage,
  CapsulePool,
  Code,
  DifficultyEnum,
  LoadingPicId,
  RedCapsulePool,
  StashableTicket,
  StyleConfig,
  Styles,
  Rogue3_StyleChallengeClass,
  DetailSubTypeDatum,
  TaskDatum,
  RewardSceneId,
  Treasures,
  Rogue2_Treasure,
  Update,
  UpgradeTickets,
  Rogue1_UpgradeTicket5StarClass,
  Rogue1_UpgradeTicketAllClass,
  Rogue1_UpgradeTicketCasterClass,
  VariationClass,
  ZoneValue,
  Module,
  Candle,
  CandleModuleConsts,
  ModuleChaos,
  ChaosData,
  ChaosDataSound,
  ChaosRange,
  LevelInfoDict,
  Rule,
  ChaosModuleConsts,
  ModuleCopper,
  CopperDatum,
  CopperDatumBuffType,
  LayerCntDesc,
  CopperDivineDatum,
  DivineType,
  ResultType,
  CopperModuleConsts,
  Dice,
  Die,
  BattleDiceId,
  DieDescription,
  DiceChoices,
  DiceEvent,
  DiceEventShowType,
  DiceEventSound,
  DicePredefine,
  DiceRuleGroup,
  ModuleDisaster,
  ErDatum,
  ModuleFragment,
  AlchemyDatum,
  TypeElement,
  OverrideConditionBandId,
  AlchemyFormulaDatum,
  FragmentBuffDatum,
  MaskType,
  FragmentDatum,
  FragmentLevelDatum,
  FragmentTypeData,
  Idea,
  FragmentModuleConsts,
  GridZone,
  BuoyItemData,
  GridZoneModuleConsts,
  ScrapSideBarStepZeroHintBannerDatum,
  ZoneMissionBannerDatum,
  BannerIcon,
  BannerText,
  NodeUpgrade,
  NodeUpgradeDataMap,
  Alchemy,
  AlchemyNodeType,
  PermItemList,
  CostItemId,
  TempItemList,
  SanCheck,
  SanCheckModuleConsts,
  SanRange,
  ModuleScrap,
  GoodsScrapDatum,
  ScrapModuleConsts,
  MoveScrapDatum,
  RangeType,
  MoveScrapRangeData,
  R1,
  Grid,
  PassiveScrapDatum,
  ScrapItemToType,
  ScrapTypeData,
  Sky,
  SkyModuleConsts,
  NodeDatum,
  EffId,
  SkySubTypeDatum,
  TotemBuff,
  TotemBuffModuleConsts,
  ColorCombineDesc,
  SubBuffs,
  Rogue3__TotemEnchant,
  TotemBuffData,
  BgIconId,
  TotemBuffDataColor,
  CombineGroupName,
  LinkedNodeTypeData,
  BlurNodeType,
  Vision,
  VisionModuleConsts,
  VisionChoice,
  VisionChoiceType,
  VisionData,
  ModuleWeather,
  SubWeatherData,
  ModuleWrath,
  WrathModuleConsts,
  WrathDatum,
  Topic,
  Config,
  HomeEntryDisplayDatum,
} from "../src/types/index.js";
import {
  RoguelikeTopicTableSchema,
  ConstantSchema,
  PredefinedCharSchema,
  RecruitTypeSchema,
  CustomizeDatumSchema,
  CommonDevelopmentSchema,
  CommonDevelopmentDevelopmentRawTextGroupSchema,
  GroupIconIdSchema,
  Rogue3__Difficulty1Schema,
  BuffDisplayInfoSchema,
  DisplayFormSchema,
  EffectTypeSchema,
  EnrollIdSchema,
  GroupIdSchema,
  ValidModeEnumSchema,
  CommonDevelopmentDevelopmentsDifficultyNodeInfosSchema,
  Rogue4_Difficulty1_ClassSchema,
  Rogue4_Difficulty1_NodeMapSchema,
  DevelopmentTokenSchema,
  DevelopmentLineSchema,
  CustomizeDatumDevelopmentRawTextGroupSchema,
  DevelopmentsSchema,
  OutbuffSchema,
  BuffIconIdSchema,
  Outbuff1_NodeTypeSchema,
  Rogue2__OutbuffSchema,
  Rogue2_Outbuff1_NodeTypeSchema,
  CustomizeDatumDevelopmentsDifficultyNodeInfosSchema,
  Rogue3__DifficultySchema,
  Rogue3_Difficulty1_NodeMapSchema,
  CustomizeDatumDifficultySchema,
  GildProbDisplaySchema,
  LeftDisasterDescSchema,
  LeftOverweightDescSchema,
  LeftWeatherDescSchema,
  LeftWrathDescSchema,
  ModeSchema,
  SkyStepDescriptionSchema,
  WeightStatusLimitDescSchema,
  EmployShopDialogDataSchema,
  EmployShopDialogDataTypesSchema,
  BuyConfirmSchema,
  BuyConfirmGroupsSchema,
  NoneSchema,
  PurpleBuySelectSchema,
  PurpleGroupsSchema,
  EndingTextSchema,
  ScrapShopDialogDataSchema,
  ScrapShopDialogDataTypesSchema,
  SpecialShopDialogSchema,
  SpecialShopDialogTypesSchema,
  FluffyBuySelectSchema,
  FluffyGroupsSchema,
  DetailSchema,
  ActivitySchema,
  ActivityTableSchema,
  SeedModeSchema,
  SeedModeRogue4_Seedmode1Schema,
  ConstDataSchema,
  OfficialSeedDataListSchema,
  BasicDatasSchema,
  BasicDatasRogue4_Seedmode1Schema,
  ArchiveCompSchema,
  ArchiveCompBuffSchema,
  BuffValueSchema,
  BuffColorSchema,
  ArchiveCompCapsuleSchema,
  CapsuleValueSchema,
  ArchiveCompChaosSchema,
  ChaoSchema,
  ArchiveCompChatSchema,
  ChatValueSchema,
  ChatItemListSchema,
  ZoneIdSchema,
  ArchiveCompCopperSchema,
  CopperTypesSchema,
  BlankSchema,
  CopperTypeSchema,
  CopperValueSchema,
  CopperArchiveTypeSchema,
  CopperGildTypeDatumSchema,
  IdSchema,
  LuckyLevelsSchema,
  HighSchema,
  LuckyLevelSchema,
  ArchiveCompDisasterSchema,
  DisasterValueSchema,
  ArchiveCompEndbookSchema,
  EndbookValueSchema,
  ClientEndbookItemDataSchema,
  ArchiveCompFragmentSchema,
  FragmentValueSchema,
  ArchiveCompRelicSchema,
  RelicRelicSchema,
  ArchiveCompScrapSchema,
  ScrapValueSchema,
  ArchiveCompTotemSchema,
  TotemValueSchema,
  PosSchema,
  ArchiveCompTrapSchema,
  TrapTrapSchema,
  Rogue1__ActiveToolSchema,
  ArchiveCompWeatherSchema,
  WeatherValueSchema,
  ArchiveCompWrathSchema,
  WrathValueSchema,
  ArchiveUnlockCondSchema,
  ArchiveUnlockCondEnrollSchema,
  EnrollArchiveTypeSchema,
  UnlockCondDescSchema,
  UnlockCondDescDescriptionSchema,
  BandRefSchema,
  BankRewardSchema,
  RewardIdSchema,
  RewardTypeSchema,
  BattleLoadingTipSchema,
  CategorySchema,
  BattleSummeryDescriptionsSchema,
  ChallengeClassSchema,
  CapsuleDictSchema,
  ChallengeElementSchema,
  ChallengeTaskSchema,
  RewardSchema,
  ItemTypeEnumSchema,
  CharBuffDataSchema,
  Rogue2_Mutation1_ClassSchema,
  Rogue2_Mutation1_BuffTypeSchema,
  BuffElementSchema,
  BlackboardSchema,
  Rogue2__Mutation4Schema,
  ChoiceSceneSchema,
  TitleIconSchema,
  ChoiceSchema,
  DisplayDataSchema,
  THintTypeSchema,
  IconEnumSchema,
  DisplayDataTypeSchema,
  LeftDecoTypeSchema,
  Rogue6_ScrapM01_EnumSchema,
  CustomTicketsSchema,
  Rogue2_CustomTicketPurifyClassSchema,
  DetailConstSchema,
  CharUpgradeTableSchema,
  EvolvePhaseSchema,
  HistoricalRecordsModeSchema,
  PlayerLevelTableSchema,
  PredefinedLevelTableSchema,
  DetailDifficultySchema,
  DisplayIconIdSchema,
  FailForceDescSchema,
  FailTitleSchema,
  NameImageSchema,
  RuleDescReplacementSchema,
  DifficultyUpgradeRelicGroupSchema,
  RelicDatumSchema,
  EndingDetailListSchema,
  EventTypeSchema,
  EndingDetailListShowTypeSchema,
  SpZoneEvtTypeSchema,
  EndingRelicDetailListSchema,
  EndingSchema,
  IconElementSchema,
  DetailEnrollSchema,
  EnrollTypeSchema,
  ExploreToolsSchema,
  Rogue3__ExploreTool1Schema,
  FailEndingsSchema,
  Ro4FailEnding1Schema,
  IconIdSchema,
  FusionDataSchema,
  VariationSchema,
  GameConstSchema,
  ItemDropTagDictSchema,
  BgmSignalSchema,
  GrandPrizeSchema,
  InitSchema,
  StyleIdSchema,
  ItemSchema,
  ObtainApproachSchema,
  RaritySchema,
  SubTypeSchema,
  TinyIconColorSchema,
  RewardItemTypeEnumSchema,
  LegacyItemSchema,
  MilestoneUpdateSchema,
  MilestoneSchema,
  MonthMissionSchema,
  TaskClassSchema,
  MonthSquadSchema,
  MonthTeamSchema,
  TeamCharSchema,
  NodeTypeDatumSchema,
  RecruitTicketsSchema,
  Rogue1_RecruitTicket5StarClassSchema,
  ExtraCharIdSchema,
  ProfessionSchema,
  RarityListSchema,
  Rogue1_RecruitTicketAllClassSchema,
  Rogue1_RecruitTicketCasterClassSchema,
  RelicParamSchema,
  CheckCharBoxParamSchema,
  CheckCharBoxTypeSchema,
  RelicTipsDataSchema,
  Rogue5__Schema,
  DetailRelicSchema,
  RollNodeDataSchema,
  ZoneSchema,
  Zone1_GroupsSchema,
  BattleEliteSchema,
  NodeTypeElementSchema,
  ZonePortalNormal5_Schema,
  ZonePortalNormal5_1_GroupsSchema,
  ZonePortalRevivalSchema,
  ZonePortalRevival3_GroupsSchema,
  ShopDialogDataSchema,
  ShopDialogDataTypesSchema,
  SquadBuffDataSchema,
  StageSchema,
  CapsulePoolSchema,
  CodeSchema,
  DifficultyEnumSchema,
  LoadingPicIdSchema,
  RedCapsulePoolSchema,
  StashableTicketSchema,
  StyleConfigSchema,
  StylesSchema,
  Rogue3_StyleChallengeClassSchema,
  DetailSubTypeDatumSchema,
  TaskDatumSchema,
  RewardSceneIdSchema,
  TreasuresSchema,
  Rogue2_TreasureSchema,
  UpdateSchema,
  UpgradeTicketsSchema,
  Rogue1_UpgradeTicket5StarClassSchema,
  Rogue1_UpgradeTicketAllClassSchema,
  Rogue1_UpgradeTicketCasterClassSchema,
  VariationClassSchema,
  ZoneValueSchema,
  ModuleSchema,
  CandleSchema,
  CandleModuleConstsSchema,
  ModuleChaosSchema,
  ChaosDataSchema,
  ChaosDataSoundSchema,
  ChaosRangeSchema,
  LevelInfoDictSchema,
  RuleSchema,
  ChaosModuleConstsSchema,
  ModuleCopperSchema,
  CopperDatumSchema,
  CopperDatumBuffTypeSchema,
  LayerCntDescSchema,
  CopperDivineDatumSchema,
  DivineTypeSchema,
  ResultTypeSchema,
  CopperModuleConstsSchema,
  DiceSchema,
  DieSchema,
  BattleDiceIdSchema,
  DieDescriptionSchema,
  DiceChoicesSchema,
  DiceEventSchema,
  DiceEventShowTypeSchema,
  DiceEventSoundSchema,
  DicePredefineSchema,
  DiceRuleGroupSchema,
  ModuleDisasterSchema,
  ErDatumSchema,
  ModuleFragmentSchema,
  AlchemyDatumSchema,
  TypeElementSchema,
  OverrideConditionBandIdSchema,
  AlchemyFormulaDatumSchema,
  FragmentBuffDatumSchema,
  MaskTypeSchema,
  FragmentDatumSchema,
  FragmentLevelDatumSchema,
  FragmentTypeDataSchema,
  IdeaSchema,
  FragmentModuleConstsSchema,
  GridZoneSchema,
  BuoyItemDataSchema,
  GridZoneModuleConstsSchema,
  ScrapSideBarStepZeroHintBannerDatumSchema,
  ZoneMissionBannerDatumSchema,
  BannerIconSchema,
  BannerTextSchema,
  NodeUpgradeSchema,
  NodeUpgradeDataMapSchema,
  AlchemySchema,
  AlchemyNodeTypeSchema,
  PermItemListSchema,
  CostItemIdSchema,
  TempItemListSchema,
  SanCheckSchema,
  SanCheckModuleConstsSchema,
  SanRangeSchema,
  ModuleScrapSchema,
  GoodsScrapDatumSchema,
  ScrapModuleConstsSchema,
  MoveScrapDatumSchema,
  RangeTypeSchema,
  MoveScrapRangeDataSchema,
  R1Schema,
  GridSchema,
  PassiveScrapDatumSchema,
  ScrapItemToTypeSchema,
  ScrapTypeDataSchema,
  SkySchema,
  SkyModuleConstsSchema,
  NodeDatumSchema,
  EffIdSchema,
  SkySubTypeDatumSchema,
  TotemBuffSchema,
  TotemBuffModuleConstsSchema,
  ColorCombineDescSchema,
  SubBuffsSchema,
  Rogue3__TotemEnchantSchema,
  TotemBuffDataSchema,
  BgIconIdSchema,
  TotemBuffDataColorSchema,
  CombineGroupNameSchema,
  LinkedNodeTypeDataSchema,
  BlurNodeTypeSchema,
  VisionSchema,
  VisionModuleConstsSchema,
  VisionChoiceSchema,
  VisionChoiceTypeSchema,
  VisionDataSchema,
  ModuleWeatherSchema,
  SubWeatherDataSchema,
  ModuleWrathSchema,
  WrathModuleConstsSchema,
  WrathDatumSchema,
  TopicSchema,
  ConfigSchema,
  HomeEntryDisplayDatumSchema,
} from "../src/schemas/index.js";

/** 比较两个类型是否完全相等。 */
type Equal<Left, Right> =
  (<Value>() => Value extends Left ? 1 : 2) extends
  (<Value>() => Value extends Right ? 1 : 2)
    ? true
    : false;

/** 要求传入的类型级布尔值为 true。 */
type Expect<Value extends true> = Value;

/** 所有生成定义的类型一致性断言集合。 */
export type RoguelikeTopicTypeAssertions = [
  Expect<Equal<RoguelikeTopicTable, z.infer<typeof RoguelikeTopicTableSchema>>>,
  Expect<Equal<Constant, z.infer<typeof ConstantSchema>>>,
  Expect<Equal<PredefinedChar, z.infer<typeof PredefinedCharSchema>>>,
  Expect<Equal<RecruitType, z.infer<typeof RecruitTypeSchema>>>,
  Expect<Equal<CustomizeDatum, z.infer<typeof CustomizeDatumSchema>>>,
  Expect<Equal<CommonDevelopment, z.infer<typeof CommonDevelopmentSchema>>>,
  Expect<Equal<CommonDevelopmentDevelopmentRawTextGroup, z.infer<typeof CommonDevelopmentDevelopmentRawTextGroupSchema>>>,
  Expect<Equal<GroupIconId, z.infer<typeof GroupIconIdSchema>>>,
  Expect<Equal<Rogue3__Difficulty1, z.infer<typeof Rogue3__Difficulty1Schema>>>,
  Expect<Equal<BuffDisplayInfo, z.infer<typeof BuffDisplayInfoSchema>>>,
  Expect<Equal<DisplayForm, z.infer<typeof DisplayFormSchema>>>,
  Expect<Equal<EffectType, z.infer<typeof EffectTypeSchema>>>,
  Expect<Equal<EnrollId, z.infer<typeof EnrollIdSchema>>>,
  Expect<Equal<GroupId, z.infer<typeof GroupIdSchema>>>,
  Expect<Equal<ValidModeEnum, z.infer<typeof ValidModeEnumSchema>>>,
  Expect<Equal<CommonDevelopmentDevelopmentsDifficultyNodeInfos, z.infer<typeof CommonDevelopmentDevelopmentsDifficultyNodeInfosSchema>>>,
  Expect<Equal<Rogue4_Difficulty1_Class, z.infer<typeof Rogue4_Difficulty1_ClassSchema>>>,
  Expect<Equal<Rogue4_Difficulty1_NodeMap, z.infer<typeof Rogue4_Difficulty1_NodeMapSchema>>>,
  Expect<Equal<DevelopmentToken, z.infer<typeof DevelopmentTokenSchema>>>,
  Expect<Equal<DevelopmentLine, z.infer<typeof DevelopmentLineSchema>>>,
  Expect<Equal<CustomizeDatumDevelopmentRawTextGroup, z.infer<typeof CustomizeDatumDevelopmentRawTextGroupSchema>>>,
  Expect<Equal<Developments, z.infer<typeof DevelopmentsSchema>>>,
  Expect<Equal<Outbuff, z.infer<typeof OutbuffSchema>>>,
  Expect<Equal<BuffIconId, z.infer<typeof BuffIconIdSchema>>>,
  Expect<Equal<Outbuff1_NodeType, z.infer<typeof Outbuff1_NodeTypeSchema>>>,
  Expect<Equal<Rogue2__Outbuff, z.infer<typeof Rogue2__OutbuffSchema>>>,
  Expect<Equal<Rogue2_Outbuff1_NodeType, z.infer<typeof Rogue2_Outbuff1_NodeTypeSchema>>>,
  Expect<Equal<CustomizeDatumDevelopmentsDifficultyNodeInfos, z.infer<typeof CustomizeDatumDevelopmentsDifficultyNodeInfosSchema>>>,
  Expect<Equal<Rogue3__Difficulty, z.infer<typeof Rogue3__DifficultySchema>>>,
  Expect<Equal<Rogue3_Difficulty1_NodeMap, z.infer<typeof Rogue3_Difficulty1_NodeMapSchema>>>,
  Expect<Equal<CustomizeDatumDifficulty, z.infer<typeof CustomizeDatumDifficultySchema>>>,
  Expect<Equal<GildProbDisplay, z.infer<typeof GildProbDisplaySchema>>>,
  Expect<Equal<LeftDisasterDesc, z.infer<typeof LeftDisasterDescSchema>>>,
  Expect<Equal<LeftOverweightDesc, z.infer<typeof LeftOverweightDescSchema>>>,
  Expect<Equal<LeftWeatherDesc, z.infer<typeof LeftWeatherDescSchema>>>,
  Expect<Equal<LeftWrathDesc, z.infer<typeof LeftWrathDescSchema>>>,
  Expect<Equal<Mode, z.infer<typeof ModeSchema>>>,
  Expect<Equal<SkyStepDescription, z.infer<typeof SkyStepDescriptionSchema>>>,
  Expect<Equal<WeightStatusLimitDesc, z.infer<typeof WeightStatusLimitDescSchema>>>,
  Expect<Equal<EmployShopDialogData, z.infer<typeof EmployShopDialogDataSchema>>>,
  Expect<Equal<EmployShopDialogDataTypes, z.infer<typeof EmployShopDialogDataTypesSchema>>>,
  Expect<Equal<BuyConfirm, z.infer<typeof BuyConfirmSchema>>>,
  Expect<Equal<BuyConfirmGroups, z.infer<typeof BuyConfirmGroupsSchema>>>,
  Expect<Equal<None, z.infer<typeof NoneSchema>>>,
  Expect<Equal<PurpleBuySelect, z.infer<typeof PurpleBuySelectSchema>>>,
  Expect<Equal<PurpleGroups, z.infer<typeof PurpleGroupsSchema>>>,
  Expect<Equal<EndingText, z.infer<typeof EndingTextSchema>>>,
  Expect<Equal<ScrapShopDialogData, z.infer<typeof ScrapShopDialogDataSchema>>>,
  Expect<Equal<ScrapShopDialogDataTypes, z.infer<typeof ScrapShopDialogDataTypesSchema>>>,
  Expect<Equal<SpecialShopDialog, z.infer<typeof SpecialShopDialogSchema>>>,
  Expect<Equal<SpecialShopDialogTypes, z.infer<typeof SpecialShopDialogTypesSchema>>>,
  Expect<Equal<FluffyBuySelect, z.infer<typeof FluffyBuySelectSchema>>>,
  Expect<Equal<FluffyGroups, z.infer<typeof FluffyGroupsSchema>>>,
  Expect<Equal<Detail, z.infer<typeof DetailSchema>>>,
  Expect<Equal<Activity, z.infer<typeof ActivitySchema>>>,
  Expect<Equal<ActivityTable, z.infer<typeof ActivityTableSchema>>>,
  Expect<Equal<SeedMode, z.infer<typeof SeedModeSchema>>>,
  Expect<Equal<SeedModeRogue4_Seedmode1, z.infer<typeof SeedModeRogue4_Seedmode1Schema>>>,
  Expect<Equal<ConstData, z.infer<typeof ConstDataSchema>>>,
  Expect<Equal<OfficialSeedDataList, z.infer<typeof OfficialSeedDataListSchema>>>,
  Expect<Equal<BasicDatas, z.infer<typeof BasicDatasSchema>>>,
  Expect<Equal<BasicDatasRogue4_Seedmode1, z.infer<typeof BasicDatasRogue4_Seedmode1Schema>>>,
  Expect<Equal<ArchiveComp, z.infer<typeof ArchiveCompSchema>>>,
  Expect<Equal<ArchiveCompBuff, z.infer<typeof ArchiveCompBuffSchema>>>,
  Expect<Equal<BuffValue, z.infer<typeof BuffValueSchema>>>,
  Expect<Equal<BuffColor, z.infer<typeof BuffColorSchema>>>,
  Expect<Equal<ArchiveCompCapsule, z.infer<typeof ArchiveCompCapsuleSchema>>>,
  Expect<Equal<CapsuleValue, z.infer<typeof CapsuleValueSchema>>>,
  Expect<Equal<ArchiveCompChaos, z.infer<typeof ArchiveCompChaosSchema>>>,
  Expect<Equal<Chao, z.infer<typeof ChaoSchema>>>,
  Expect<Equal<ArchiveCompChat, z.infer<typeof ArchiveCompChatSchema>>>,
  Expect<Equal<ChatValue, z.infer<typeof ChatValueSchema>>>,
  Expect<Equal<ChatItemList, z.infer<typeof ChatItemListSchema>>>,
  Expect<Equal<ZoneId, z.infer<typeof ZoneIdSchema>>>,
  Expect<Equal<ArchiveCompCopper, z.infer<typeof ArchiveCompCopperSchema>>>,
  Expect<Equal<CopperTypes, z.infer<typeof CopperTypesSchema>>>,
  Expect<Equal<Blank, z.infer<typeof BlankSchema>>>,
  Expect<Equal<CopperType, z.infer<typeof CopperTypeSchema>>>,
  Expect<Equal<CopperValue, z.infer<typeof CopperValueSchema>>>,
  Expect<Equal<CopperArchiveType, z.infer<typeof CopperArchiveTypeSchema>>>,
  Expect<Equal<CopperGildTypeDatum, z.infer<typeof CopperGildTypeDatumSchema>>>,
  Expect<Equal<Id, z.infer<typeof IdSchema>>>,
  Expect<Equal<LuckyLevels, z.infer<typeof LuckyLevelsSchema>>>,
  Expect<Equal<High, z.infer<typeof HighSchema>>>,
  Expect<Equal<LuckyLevel, z.infer<typeof LuckyLevelSchema>>>,
  Expect<Equal<ArchiveCompDisaster, z.infer<typeof ArchiveCompDisasterSchema>>>,
  Expect<Equal<DisasterValue, z.infer<typeof DisasterValueSchema>>>,
  Expect<Equal<ArchiveCompEndbook, z.infer<typeof ArchiveCompEndbookSchema>>>,
  Expect<Equal<EndbookValue, z.infer<typeof EndbookValueSchema>>>,
  Expect<Equal<ClientEndbookItemData, z.infer<typeof ClientEndbookItemDataSchema>>>,
  Expect<Equal<ArchiveCompFragment, z.infer<typeof ArchiveCompFragmentSchema>>>,
  Expect<Equal<FragmentValue, z.infer<typeof FragmentValueSchema>>>,
  Expect<Equal<ArchiveCompRelic, z.infer<typeof ArchiveCompRelicSchema>>>,
  Expect<Equal<RelicRelic, z.infer<typeof RelicRelicSchema>>>,
  Expect<Equal<ArchiveCompScrap, z.infer<typeof ArchiveCompScrapSchema>>>,
  Expect<Equal<ScrapValue, z.infer<typeof ScrapValueSchema>>>,
  Expect<Equal<ArchiveCompTotem, z.infer<typeof ArchiveCompTotemSchema>>>,
  Expect<Equal<TotemValue, z.infer<typeof TotemValueSchema>>>,
  Expect<Equal<Pos, z.infer<typeof PosSchema>>>,
  Expect<Equal<ArchiveCompTrap, z.infer<typeof ArchiveCompTrapSchema>>>,
  Expect<Equal<TrapTrap, z.infer<typeof TrapTrapSchema>>>,
  Expect<Equal<Rogue1__ActiveTool, z.infer<typeof Rogue1__ActiveToolSchema>>>,
  Expect<Equal<ArchiveCompWeather, z.infer<typeof ArchiveCompWeatherSchema>>>,
  Expect<Equal<WeatherValue, z.infer<typeof WeatherValueSchema>>>,
  Expect<Equal<ArchiveCompWrath, z.infer<typeof ArchiveCompWrathSchema>>>,
  Expect<Equal<WrathValue, z.infer<typeof WrathValueSchema>>>,
  Expect<Equal<ArchiveUnlockCond, z.infer<typeof ArchiveUnlockCondSchema>>>,
  Expect<Equal<ArchiveUnlockCondEnroll, z.infer<typeof ArchiveUnlockCondEnrollSchema>>>,
  Expect<Equal<EnrollArchiveType, z.infer<typeof EnrollArchiveTypeSchema>>>,
  Expect<Equal<UnlockCondDesc, z.infer<typeof UnlockCondDescSchema>>>,
  Expect<Equal<UnlockCondDescDescription, z.infer<typeof UnlockCondDescDescriptionSchema>>>,
  Expect<Equal<BandRef, z.infer<typeof BandRefSchema>>>,
  Expect<Equal<BankReward, z.infer<typeof BankRewardSchema>>>,
  Expect<Equal<RewardId, z.infer<typeof RewardIdSchema>>>,
  Expect<Equal<RewardType, z.infer<typeof RewardTypeSchema>>>,
  Expect<Equal<BattleLoadingTip, z.infer<typeof BattleLoadingTipSchema>>>,
  Expect<Equal<Category, z.infer<typeof CategorySchema>>>,
  Expect<Equal<BattleSummeryDescriptions, z.infer<typeof BattleSummeryDescriptionsSchema>>>,
  Expect<Equal<ChallengeClass, z.infer<typeof ChallengeClassSchema>>>,
  Expect<Equal<CapsuleDict, z.infer<typeof CapsuleDictSchema>>>,
  Expect<Equal<ChallengeElement, z.infer<typeof ChallengeElementSchema>>>,
  Expect<Equal<ChallengeTask, z.infer<typeof ChallengeTaskSchema>>>,
  Expect<Equal<Reward, z.infer<typeof RewardSchema>>>,
  Expect<Equal<ItemTypeEnum, z.infer<typeof ItemTypeEnumSchema>>>,
  Expect<Equal<CharBuffData, z.infer<typeof CharBuffDataSchema>>>,
  Expect<Equal<Rogue2_Mutation1_Class, z.infer<typeof Rogue2_Mutation1_ClassSchema>>>,
  Expect<Equal<Rogue2_Mutation1_BuffType, z.infer<typeof Rogue2_Mutation1_BuffTypeSchema>>>,
  Expect<Equal<BuffElement, z.infer<typeof BuffElementSchema>>>,
  Expect<Equal<Blackboard, z.infer<typeof BlackboardSchema>>>,
  Expect<Equal<Rogue2__Mutation4, z.infer<typeof Rogue2__Mutation4Schema>>>,
  Expect<Equal<ChoiceScene, z.infer<typeof ChoiceSceneSchema>>>,
  Expect<Equal<TitleIcon, z.infer<typeof TitleIconSchema>>>,
  Expect<Equal<Choice, z.infer<typeof ChoiceSchema>>>,
  Expect<Equal<DisplayData, z.infer<typeof DisplayDataSchema>>>,
  Expect<Equal<THintType, z.infer<typeof THintTypeSchema>>>,
  Expect<Equal<IconEnum, z.infer<typeof IconEnumSchema>>>,
  Expect<Equal<DisplayDataType, z.infer<typeof DisplayDataTypeSchema>>>,
  Expect<Equal<LeftDecoType, z.infer<typeof LeftDecoTypeSchema>>>,
  Expect<Equal<Rogue6_ScrapM01_Enum, z.infer<typeof Rogue6_ScrapM01_EnumSchema>>>,
  Expect<Equal<CustomTickets, z.infer<typeof CustomTicketsSchema>>>,
  Expect<Equal<Rogue2_CustomTicketPurifyClass, z.infer<typeof Rogue2_CustomTicketPurifyClassSchema>>>,
  Expect<Equal<DetailConst, z.infer<typeof DetailConstSchema>>>,
  Expect<Equal<CharUpgradeTable, z.infer<typeof CharUpgradeTableSchema>>>,
  Expect<Equal<EvolvePhase, z.infer<typeof EvolvePhaseSchema>>>,
  Expect<Equal<HistoricalRecordsMode, z.infer<typeof HistoricalRecordsModeSchema>>>,
  Expect<Equal<PlayerLevelTable, z.infer<typeof PlayerLevelTableSchema>>>,
  Expect<Equal<PredefinedLevelTable, z.infer<typeof PredefinedLevelTableSchema>>>,
  Expect<Equal<DetailDifficulty, z.infer<typeof DetailDifficultySchema>>>,
  Expect<Equal<DisplayIconId, z.infer<typeof DisplayIconIdSchema>>>,
  Expect<Equal<FailForceDesc, z.infer<typeof FailForceDescSchema>>>,
  Expect<Equal<FailTitle, z.infer<typeof FailTitleSchema>>>,
  Expect<Equal<NameImage, z.infer<typeof NameImageSchema>>>,
  Expect<Equal<RuleDescReplacement, z.infer<typeof RuleDescReplacementSchema>>>,
  Expect<Equal<DifficultyUpgradeRelicGroup, z.infer<typeof DifficultyUpgradeRelicGroupSchema>>>,
  Expect<Equal<RelicDatum, z.infer<typeof RelicDatumSchema>>>,
  Expect<Equal<EndingDetailList, z.infer<typeof EndingDetailListSchema>>>,
  Expect<Equal<EventType, z.infer<typeof EventTypeSchema>>>,
  Expect<Equal<EndingDetailListShowType, z.infer<typeof EndingDetailListShowTypeSchema>>>,
  Expect<Equal<SpZoneEvtType, z.infer<typeof SpZoneEvtTypeSchema>>>,
  Expect<Equal<EndingRelicDetailList, z.infer<typeof EndingRelicDetailListSchema>>>,
  Expect<Equal<Ending, z.infer<typeof EndingSchema>>>,
  Expect<Equal<IconElement, z.infer<typeof IconElementSchema>>>,
  Expect<Equal<DetailEnroll, z.infer<typeof DetailEnrollSchema>>>,
  Expect<Equal<EnrollType, z.infer<typeof EnrollTypeSchema>>>,
  Expect<Equal<ExploreTools, z.infer<typeof ExploreToolsSchema>>>,
  Expect<Equal<Rogue3__ExploreTool1, z.infer<typeof Rogue3__ExploreTool1Schema>>>,
  Expect<Equal<FailEndings, z.infer<typeof FailEndingsSchema>>>,
  Expect<Equal<Ro4FailEnding1, z.infer<typeof Ro4FailEnding1Schema>>>,
  Expect<Equal<IconId, z.infer<typeof IconIdSchema>>>,
  Expect<Equal<FusionData, z.infer<typeof FusionDataSchema>>>,
  Expect<Equal<Variation, z.infer<typeof VariationSchema>>>,
  Expect<Equal<GameConst, z.infer<typeof GameConstSchema>>>,
  Expect<Equal<ItemDropTagDict, z.infer<typeof ItemDropTagDictSchema>>>,
  Expect<Equal<BgmSignal, z.infer<typeof BgmSignalSchema>>>,
  Expect<Equal<GrandPrize, z.infer<typeof GrandPrizeSchema>>>,
  Expect<Equal<Init, z.infer<typeof InitSchema>>>,
  Expect<Equal<StyleId, z.infer<typeof StyleIdSchema>>>,
  Expect<Equal<Item, z.infer<typeof ItemSchema>>>,
  Expect<Equal<ObtainApproach, z.infer<typeof ObtainApproachSchema>>>,
  Expect<Equal<Rarity, z.infer<typeof RaritySchema>>>,
  Expect<Equal<SubType, z.infer<typeof SubTypeSchema>>>,
  Expect<Equal<TinyIconColor, z.infer<typeof TinyIconColorSchema>>>,
  Expect<Equal<RewardItemTypeEnum, z.infer<typeof RewardItemTypeEnumSchema>>>,
  Expect<Equal<LegacyItem, z.infer<typeof LegacyItemSchema>>>,
  Expect<Equal<MilestoneUpdate, z.infer<typeof MilestoneUpdateSchema>>>,
  Expect<Equal<Milestone, z.infer<typeof MilestoneSchema>>>,
  Expect<Equal<MonthMission, z.infer<typeof MonthMissionSchema>>>,
  Expect<Equal<TaskClass, z.infer<typeof TaskClassSchema>>>,
  Expect<Equal<MonthSquad, z.infer<typeof MonthSquadSchema>>>,
  Expect<Equal<MonthTeam, z.infer<typeof MonthTeamSchema>>>,
  Expect<Equal<TeamChar, z.infer<typeof TeamCharSchema>>>,
  Expect<Equal<NodeTypeDatum, z.infer<typeof NodeTypeDatumSchema>>>,
  Expect<Equal<RecruitTickets, z.infer<typeof RecruitTicketsSchema>>>,
  Expect<Equal<Rogue1_RecruitTicket5StarClass, z.infer<typeof Rogue1_RecruitTicket5StarClassSchema>>>,
  Expect<Equal<ExtraCharId, z.infer<typeof ExtraCharIdSchema>>>,
  Expect<Equal<Profession, z.infer<typeof ProfessionSchema>>>,
  Expect<Equal<RarityList, z.infer<typeof RarityListSchema>>>,
  Expect<Equal<Rogue1_RecruitTicketAllClass, z.infer<typeof Rogue1_RecruitTicketAllClassSchema>>>,
  Expect<Equal<Rogue1_RecruitTicketCasterClass, z.infer<typeof Rogue1_RecruitTicketCasterClassSchema>>>,
  Expect<Equal<RelicParam, z.infer<typeof RelicParamSchema>>>,
  Expect<Equal<CheckCharBoxParam, z.infer<typeof CheckCharBoxParamSchema>>>,
  Expect<Equal<CheckCharBoxType, z.infer<typeof CheckCharBoxTypeSchema>>>,
  Expect<Equal<RelicTipsData, z.infer<typeof RelicTipsDataSchema>>>,
  Expect<Equal<Rogue5__, z.infer<typeof Rogue5__Schema>>>,
  Expect<Equal<DetailRelic, z.infer<typeof DetailRelicSchema>>>,
  Expect<Equal<RollNodeData, z.infer<typeof RollNodeDataSchema>>>,
  Expect<Equal<Zone, z.infer<typeof ZoneSchema>>>,
  Expect<Equal<Zone1_Groups, z.infer<typeof Zone1_GroupsSchema>>>,
  Expect<Equal<BattleElite, z.infer<typeof BattleEliteSchema>>>,
  Expect<Equal<NodeTypeElement, z.infer<typeof NodeTypeElementSchema>>>,
  Expect<Equal<ZonePortalNormal5_, z.infer<typeof ZonePortalNormal5_Schema>>>,
  Expect<Equal<ZonePortalNormal5_1_Groups, z.infer<typeof ZonePortalNormal5_1_GroupsSchema>>>,
  Expect<Equal<ZonePortalRevival, z.infer<typeof ZonePortalRevivalSchema>>>,
  Expect<Equal<ZonePortalRevival3_Groups, z.infer<typeof ZonePortalRevival3_GroupsSchema>>>,
  Expect<Equal<ShopDialogData, z.infer<typeof ShopDialogDataSchema>>>,
  Expect<Equal<ShopDialogDataTypes, z.infer<typeof ShopDialogDataTypesSchema>>>,
  Expect<Equal<SquadBuffData, z.infer<typeof SquadBuffDataSchema>>>,
  Expect<Equal<Stage, z.infer<typeof StageSchema>>>,
  Expect<Equal<CapsulePool, z.infer<typeof CapsulePoolSchema>>>,
  Expect<Equal<Code, z.infer<typeof CodeSchema>>>,
  Expect<Equal<DifficultyEnum, z.infer<typeof DifficultyEnumSchema>>>,
  Expect<Equal<LoadingPicId, z.infer<typeof LoadingPicIdSchema>>>,
  Expect<Equal<RedCapsulePool, z.infer<typeof RedCapsulePoolSchema>>>,
  Expect<Equal<StashableTicket, z.infer<typeof StashableTicketSchema>>>,
  Expect<Equal<StyleConfig, z.infer<typeof StyleConfigSchema>>>,
  Expect<Equal<Styles, z.infer<typeof StylesSchema>>>,
  Expect<Equal<Rogue3_StyleChallengeClass, z.infer<typeof Rogue3_StyleChallengeClassSchema>>>,
  Expect<Equal<DetailSubTypeDatum, z.infer<typeof DetailSubTypeDatumSchema>>>,
  Expect<Equal<TaskDatum, z.infer<typeof TaskDatumSchema>>>,
  Expect<Equal<RewardSceneId, z.infer<typeof RewardSceneIdSchema>>>,
  Expect<Equal<Treasures, z.infer<typeof TreasuresSchema>>>,
  Expect<Equal<Rogue2_Treasure, z.infer<typeof Rogue2_TreasureSchema>>>,
  Expect<Equal<Update, z.infer<typeof UpdateSchema>>>,
  Expect<Equal<UpgradeTickets, z.infer<typeof UpgradeTicketsSchema>>>,
  Expect<Equal<Rogue1_UpgradeTicket5StarClass, z.infer<typeof Rogue1_UpgradeTicket5StarClassSchema>>>,
  Expect<Equal<Rogue1_UpgradeTicketAllClass, z.infer<typeof Rogue1_UpgradeTicketAllClassSchema>>>,
  Expect<Equal<Rogue1_UpgradeTicketCasterClass, z.infer<typeof Rogue1_UpgradeTicketCasterClassSchema>>>,
  Expect<Equal<VariationClass, z.infer<typeof VariationClassSchema>>>,
  Expect<Equal<ZoneValue, z.infer<typeof ZoneValueSchema>>>,
  Expect<Equal<Module, z.infer<typeof ModuleSchema>>>,
  Expect<Equal<Candle, z.infer<typeof CandleSchema>>>,
  Expect<Equal<CandleModuleConsts, z.infer<typeof CandleModuleConstsSchema>>>,
  Expect<Equal<ModuleChaos, z.infer<typeof ModuleChaosSchema>>>,
  Expect<Equal<ChaosData, z.infer<typeof ChaosDataSchema>>>,
  Expect<Equal<ChaosDataSound, z.infer<typeof ChaosDataSoundSchema>>>,
  Expect<Equal<ChaosRange, z.infer<typeof ChaosRangeSchema>>>,
  Expect<Equal<LevelInfoDict, z.infer<typeof LevelInfoDictSchema>>>,
  Expect<Equal<Rule, z.infer<typeof RuleSchema>>>,
  Expect<Equal<ChaosModuleConsts, z.infer<typeof ChaosModuleConstsSchema>>>,
  Expect<Equal<ModuleCopper, z.infer<typeof ModuleCopperSchema>>>,
  Expect<Equal<CopperDatum, z.infer<typeof CopperDatumSchema>>>,
  Expect<Equal<CopperDatumBuffType, z.infer<typeof CopperDatumBuffTypeSchema>>>,
  Expect<Equal<LayerCntDesc, z.infer<typeof LayerCntDescSchema>>>,
  Expect<Equal<CopperDivineDatum, z.infer<typeof CopperDivineDatumSchema>>>,
  Expect<Equal<DivineType, z.infer<typeof DivineTypeSchema>>>,
  Expect<Equal<ResultType, z.infer<typeof ResultTypeSchema>>>,
  Expect<Equal<CopperModuleConsts, z.infer<typeof CopperModuleConstsSchema>>>,
  Expect<Equal<Dice, z.infer<typeof DiceSchema>>>,
  Expect<Equal<Die, z.infer<typeof DieSchema>>>,
  Expect<Equal<BattleDiceId, z.infer<typeof BattleDiceIdSchema>>>,
  Expect<Equal<DieDescription, z.infer<typeof DieDescriptionSchema>>>,
  Expect<Equal<DiceChoices, z.infer<typeof DiceChoicesSchema>>>,
  Expect<Equal<DiceEvent, z.infer<typeof DiceEventSchema>>>,
  Expect<Equal<DiceEventShowType, z.infer<typeof DiceEventShowTypeSchema>>>,
  Expect<Equal<DiceEventSound, z.infer<typeof DiceEventSoundSchema>>>,
  Expect<Equal<DicePredefine, z.infer<typeof DicePredefineSchema>>>,
  Expect<Equal<DiceRuleGroup, z.infer<typeof DiceRuleGroupSchema>>>,
  Expect<Equal<ModuleDisaster, z.infer<typeof ModuleDisasterSchema>>>,
  Expect<Equal<ErDatum, z.infer<typeof ErDatumSchema>>>,
  Expect<Equal<ModuleFragment, z.infer<typeof ModuleFragmentSchema>>>,
  Expect<Equal<AlchemyDatum, z.infer<typeof AlchemyDatumSchema>>>,
  Expect<Equal<TypeElement, z.infer<typeof TypeElementSchema>>>,
  Expect<Equal<OverrideConditionBandId, z.infer<typeof OverrideConditionBandIdSchema>>>,
  Expect<Equal<AlchemyFormulaDatum, z.infer<typeof AlchemyFormulaDatumSchema>>>,
  Expect<Equal<FragmentBuffDatum, z.infer<typeof FragmentBuffDatumSchema>>>,
  Expect<Equal<MaskType, z.infer<typeof MaskTypeSchema>>>,
  Expect<Equal<FragmentDatum, z.infer<typeof FragmentDatumSchema>>>,
  Expect<Equal<FragmentLevelDatum, z.infer<typeof FragmentLevelDatumSchema>>>,
  Expect<Equal<FragmentTypeData, z.infer<typeof FragmentTypeDataSchema>>>,
  Expect<Equal<Idea, z.infer<typeof IdeaSchema>>>,
  Expect<Equal<FragmentModuleConsts, z.infer<typeof FragmentModuleConstsSchema>>>,
  Expect<Equal<GridZone, z.infer<typeof GridZoneSchema>>>,
  Expect<Equal<BuoyItemData, z.infer<typeof BuoyItemDataSchema>>>,
  Expect<Equal<GridZoneModuleConsts, z.infer<typeof GridZoneModuleConstsSchema>>>,
  Expect<Equal<ScrapSideBarStepZeroHintBannerDatum, z.infer<typeof ScrapSideBarStepZeroHintBannerDatumSchema>>>,
  Expect<Equal<ZoneMissionBannerDatum, z.infer<typeof ZoneMissionBannerDatumSchema>>>,
  Expect<Equal<BannerIcon, z.infer<typeof BannerIconSchema>>>,
  Expect<Equal<BannerText, z.infer<typeof BannerTextSchema>>>,
  Expect<Equal<NodeUpgrade, z.infer<typeof NodeUpgradeSchema>>>,
  Expect<Equal<NodeUpgradeDataMap, z.infer<typeof NodeUpgradeDataMapSchema>>>,
  Expect<Equal<Alchemy, z.infer<typeof AlchemySchema>>>,
  Expect<Equal<AlchemyNodeType, z.infer<typeof AlchemyNodeTypeSchema>>>,
  Expect<Equal<PermItemList, z.infer<typeof PermItemListSchema>>>,
  Expect<Equal<CostItemId, z.infer<typeof CostItemIdSchema>>>,
  Expect<Equal<TempItemList, z.infer<typeof TempItemListSchema>>>,
  Expect<Equal<SanCheck, z.infer<typeof SanCheckSchema>>>,
  Expect<Equal<SanCheckModuleConsts, z.infer<typeof SanCheckModuleConstsSchema>>>,
  Expect<Equal<SanRange, z.infer<typeof SanRangeSchema>>>,
  Expect<Equal<ModuleScrap, z.infer<typeof ModuleScrapSchema>>>,
  Expect<Equal<GoodsScrapDatum, z.infer<typeof GoodsScrapDatumSchema>>>,
  Expect<Equal<ScrapModuleConsts, z.infer<typeof ScrapModuleConstsSchema>>>,
  Expect<Equal<MoveScrapDatum, z.infer<typeof MoveScrapDatumSchema>>>,
  Expect<Equal<RangeType, z.infer<typeof RangeTypeSchema>>>,
  Expect<Equal<MoveScrapRangeData, z.infer<typeof MoveScrapRangeDataSchema>>>,
  Expect<Equal<R1, z.infer<typeof R1Schema>>>,
  Expect<Equal<Grid, z.infer<typeof GridSchema>>>,
  Expect<Equal<PassiveScrapDatum, z.infer<typeof PassiveScrapDatumSchema>>>,
  Expect<Equal<ScrapItemToType, z.infer<typeof ScrapItemToTypeSchema>>>,
  Expect<Equal<ScrapTypeData, z.infer<typeof ScrapTypeDataSchema>>>,
  Expect<Equal<Sky, z.infer<typeof SkySchema>>>,
  Expect<Equal<SkyModuleConsts, z.infer<typeof SkyModuleConstsSchema>>>,
  Expect<Equal<NodeDatum, z.infer<typeof NodeDatumSchema>>>,
  Expect<Equal<EffId, z.infer<typeof EffIdSchema>>>,
  Expect<Equal<SkySubTypeDatum, z.infer<typeof SkySubTypeDatumSchema>>>,
  Expect<Equal<TotemBuff, z.infer<typeof TotemBuffSchema>>>,
  Expect<Equal<TotemBuffModuleConsts, z.infer<typeof TotemBuffModuleConstsSchema>>>,
  Expect<Equal<ColorCombineDesc, z.infer<typeof ColorCombineDescSchema>>>,
  Expect<Equal<SubBuffs, z.infer<typeof SubBuffsSchema>>>,
  Expect<Equal<Rogue3__TotemEnchant, z.infer<typeof Rogue3__TotemEnchantSchema>>>,
  Expect<Equal<TotemBuffData, z.infer<typeof TotemBuffDataSchema>>>,
  Expect<Equal<BgIconId, z.infer<typeof BgIconIdSchema>>>,
  Expect<Equal<TotemBuffDataColor, z.infer<typeof TotemBuffDataColorSchema>>>,
  Expect<Equal<CombineGroupName, z.infer<typeof CombineGroupNameSchema>>>,
  Expect<Equal<LinkedNodeTypeData, z.infer<typeof LinkedNodeTypeDataSchema>>>,
  Expect<Equal<BlurNodeType, z.infer<typeof BlurNodeTypeSchema>>>,
  Expect<Equal<Vision, z.infer<typeof VisionSchema>>>,
  Expect<Equal<VisionModuleConsts, z.infer<typeof VisionModuleConstsSchema>>>,
  Expect<Equal<VisionChoice, z.infer<typeof VisionChoiceSchema>>>,
  Expect<Equal<VisionChoiceType, z.infer<typeof VisionChoiceTypeSchema>>>,
  Expect<Equal<VisionData, z.infer<typeof VisionDataSchema>>>,
  Expect<Equal<ModuleWeather, z.infer<typeof ModuleWeatherSchema>>>,
  Expect<Equal<SubWeatherData, z.infer<typeof SubWeatherDataSchema>>>,
  Expect<Equal<ModuleWrath, z.infer<typeof ModuleWrathSchema>>>,
  Expect<Equal<WrathModuleConsts, z.infer<typeof WrathModuleConstsSchema>>>,
  Expect<Equal<WrathDatum, z.infer<typeof WrathDatumSchema>>>,
  Expect<Equal<Topic, z.infer<typeof TopicSchema>>>,
  Expect<Equal<Config, z.infer<typeof ConfigSchema>>>,
  Expect<Equal<HomeEntryDisplayDatum, z.infer<typeof HomeEntryDisplayDatumSchema>>>,
];
