/**

 * JSON 逻辑模块 `customize-data/ending-text/ending-text` 的 Zod Schema。

 */

import { z } from "zod";

import type { EndingText } from "../../../../types/roguelike-topic-table/customize-data/ending-text/ending-text.types.js";

/**
 * roguelike_topic_table.json 中 EndingText 的运行时校验结构。
 */
export const EndingTextSchema = z
  .strictObject({
    summaryVariation: z.string().optional(),
    summaryFusion: z.string().optional(),
    summaryCapsule: z.string().optional(),
    summaryActor: z.string().optional(),
    summaryTop: z.string().optional(),
    summaryZone: z.string().optional(),
    summaryEnding: z.string().optional(),
    summaryDifficultyZone: z.union([z.null(), z.string()]).optional(),
    summaryDifficultyEnding: z.union([z.null(), z.string()]).optional(),
    summaryMode: z.string().optional(),
    summaryGroup: z.string().optional(),
    summarySupport: z.string().optional(),
    summaryNormalRecruit: z.string().optional(),
    summaryDirectRecruit: z.string().optional(),
    summaryFriendRecruit: z.string().optional(),
    summaryFreeRecruit: z.string().optional(),
    summaryMonthRecruit: z.string().optional(),
    summaryUpgrade: z.string().optional(),
    summaryCompleteEnding: z.string().optional(),
    summaryEachZone: z.string().optional(),
    summaryMeetSpZone: z.union([z.null(), z.string()]).optional(),
    summaryPerfectBattle: z.string().optional(),
    summaryMeetBattle: z.string().optional(),
    summaryMeetEvent: z.string().optional(),
    summaryMeetShop: z.string().optional(),
    summaryMeetTreasure: z.string().optional(),
    summaryMeetSecretpath: z.union([z.null(), z.string()]).optional(),
    summaryExchangeRelic: z.union([z.null(), z.string()]).optional(),
    summaryMeetTrade: z.union([z.null(), z.string()]).optional(),
    summaryBuy: z.string().optional(),
    summaryBuyWithPriceId: z.union([z.null(), z.string()]).optional(),
    summaryInvest: z.string().optional(),
    summaryGet: z.string().optional(),
    summaryRelic: z.string().optional(),
    summarySafeHouse: z.string().optional(),
    summaryFailEnd: z.string().optional(),
    summaryStockRecruitTicket: z.union([z.null(), z.string()]).optional(),
    summaryDuelWin: z.union([z.null(), z.string()]).optional(),
    summaryDuelTie: z.union([z.null(), z.string()]).optional(),
    summaryDuelLose: z.union([z.null(), z.string()]).optional(),
    summaryExpeditionGo: z.union([z.null(), z.string()]).optional(),
    summaryExpeditionBack: z.union([z.null(), z.string()]).optional(),
    summaryMutation: z.string().optional(),
    summaryDice: z.string().optional(),
    summaryDiceResultGood: z.string().optional(),
    summaryDiceResultNormal: z.string().optional(),
    summaryDiceResultBad: z.string().optional(),
    summaryDiceResultDesc: z.string().optional(),
    summaryCommuDesc: z.string().optional(),
    summaryHiddenDesc: z.string().optional(),
    summaryKnightDesc: z.string().optional(),
    summaryGoldDesc: z.string().optional(),
    summaryPracticeDesc: z.string().optional(),
    summaryCommuEmptyDesc: z.string().optional(),
    summaryCommuNotEmptyDesc: z.string().optional(),
    summaryHiddenPassedDesc: z.string().optional(),
    summaryHiddenNotPassedDesc: z.string().optional(),
    summaryKnightPassedDesc: z.string().optional(),
    summaryKnightNotPassedDesc: z.string().optional(),
    summaryGoldThreshold: z.number().optional(),
    summaryGoldHighDesc: z.string().optional(),
    summaryGoldLowDesc: z.string().optional(),
    summaryPracticeThreshold: z.number().optional(),
    summaryPracticeHighDesc: z.string().optional(),
    summaryPracticeLowDesc: z.string().optional(),
    summaryGetTotem: z.string().optional(),
    summaryDemoPointUp: z.string().optional(),
    summaryDemoPointDown: z.string().optional(),
    summaryDemoGradeUp: z.string().optional(),
    summaryDemoGradeDown: z.string().optional(),
    summaryVisionPointUp: z.string().optional(),
    summaryVisionPointDown: z.string().optional(),
    summaryVisionGradeUp: z.string().optional(),
    summaryVisionGradeDown: z.string().optional(),
    summaryFightWin: z.string().optional(),
    summaryFightFail: z.string().optional(),
    summaryExchangeTotem: z.string().optional(),
    summaryUseTotem: z.string().optional(),
    summaryVisionGrade: z.string().optional(),
    summaryGetFragment: z.string().optional(),
    summaryUseIdea: z.string().optional(),
    summaryUseFood: z.string().optional(),
    summaryDropFragment: z.string().optional(),
    summaryMeetDisaster: z.string().optional(),
    summaryLeaveDisaster: z.string().optional(),
    summaryEnterAlchemy: z.string().optional(),
    summaryAlchemyOthers: z.string().optional(),
    summaryAlchemyFragment: z.string().optional(),
    summaryWeightOverweight: z.string().optional(),
    summaryWeightLimit: z.string().optional(),
    summaryWeightSafe: z.string().optional(),
    summaryPermUpgrade: z.string().optional(),
    summaryTempUpgrade: z.string().optional(),
    summarySellFragment: z.string().optional(),
    summaryGetCopper: z.string().optional(),
    summaryLostCopper: z.string().optional(),
    summaryDrawCopper: z.string().optional(),
    summaryCopperResultGood: z.string().optional(),
    summaryCopperResultBad: z.string().optional(),
    summaryCopperResultNormal: z.string().optional(),
    summaryCopperCheckSuccess: z.string().optional(),
    summaryCopperCheckFail: z.string().optional(),
    summaryCopperCheckNormal: z.string().optional(),
    summaryMeetWrath: z.string().optional(),
    summaryExpeditionGoEndingFour: z.string().optional(),
    summaryExpeditionBackEndingFour: z.string().optional(),
    summaryExpeditionBackCandle: z.string().optional(),
    summaryExpeditionGoEnding: z.string().optional(),
    summaryExpeditionBackEnding: z.string().optional(),
    summaryHoldCandle: z.string().optional(),
    summaryHoldCandleRecruit: z.string().optional(),
    summaryHoldCandleUpgrade: z.string().optional(),
    summaryExpeditionEndingFourToFive: z.string().optional(),
    summaryExchangeSpZoneGet: z.string().optional(),
    summaryMeetShopSpZone: z.string().optional(),
    summaryBattleFailSpZone: z.string().optional(),
    summaryMeetEventLock: z.string().optional(),
    summaryTreasureSpZone: z.string().optional(),
    summaryMeetExchangeSpZone: z.string().optional(),
    summaryMeetTradeSpZone: z.string().optional(),
    summaryScrapGot: z.string().optional(),
    summaryScrapSold: z.string().optional(),
    summaryScrapLost: z.string().optional(),
    summaryScrapMove: z.string().optional(),
    summaryScrapBuff: z.string().optional(),
    summaryScrapLegacy: z.string().optional(),
    summaryMeetWeather: z.string().optional(),
    summaryWeatherClear: z.string().optional(),
    summaryBubbleBandit: z.string().optional(),
    summaryBubbleTreasure: z.string().optional(),
    summaryBubbleEvent: z.string().optional(),
    summarySavageCamp: z.string().optional(),
    summaryScrapShop: z.string().optional(),
    summaryScrapShopBuy: z.string().optional(),
    summaryScrapShopIdentify: z.string().optional(),
    summaryDoor: z.string().optional(),
    summaryTreeHole: z.string().optional(),
    summaryEvacuate: z.string().optional(),
    summaryEmployCamp: z.string().optional(),
    summaryEmployRecruit: z.string().optional(),
    summaryMercenaryLeave: z.string().optional(),
    summaryEncounterBattleWin: z.string().optional(),
    summaryEncounterBattleLose: z.string().optional(),
    summaryExchangeScrap: z.string().optional(),
  })
  .describe(
    "roguelike_topic_table.json 中 EndingText 的运行时校验结构。",
  ) satisfies z.ZodType<EndingText>;
